import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from './home.module.scss'
import { gsap } from 'gsap'
import { useEffect, useRef, useState } from 'react'

const Home: NextPage = () => {
  // const [disappear, setDisappear] = useState(false)
  const lineRef = useRef(null)
  const overlayRef = useRef(null)
  // const textAnimation = gsap.from(lineRef.current, { yPercent: 100 })

  const disappearOverlay = gsap.to(overlayRef, { opacity: 0 })

  useEffect(() => {
    const textTimeline = gsap.timeline()
    textTimeline.from('.titles', { yPercent: 100, delay: 0.5 })
    textTimeline.to('.fill', {
      webkitTextFillColor: '#5C068C',
      duration: 2,
      delay: 1,
    })
  }, [])

  const disappear = () => {
    disappearOverlay.play()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div
          className={styles['home-overlay']}
          ref={overlayRef}
          onClick={disappear}
        >
          <div>
            <h2 className="titles" ref={lineRef}>
              The sky calls to us{' '}
            </h2>
            {/* citizens of */}
          </div>
          {/* <div>
            <h2>distant epochs</h2>
          </div> */}
          <div>
            <h2 className="titles">
              <span className="fill">dream</span> of the mind's
            </h2>
          </div>
          {/* <div>
            <h2>dispassionate extraterrestrial observer</h2>
          </div> */}
          <div>
            <h2 className="titles">eye. A mote of dust</h2>
          </div>
          <div>
            <h2 className="titles">suspended</h2>
          </div>
          <div>
            <h2 className="titles">
              in a <span className="fill">sunbeam</span>.
            </h2>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
